image: ubuntu:16.04

stages:
  - build
  - smoke_test
  - test
  - deploy

linux:build:
  script:
    - ./configure --auto
    - cd build
    - make -j4
    - make install
    - cd ..
    - pwd
    - find /usr/local/
    - mkdir -p install/usr/
    - cp -r /usr/local/ install/usr/
  artifacts:
    expire_in: 1 day
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - install/
  stage: build
  image: butitsnotme/build-env:latest
  tags:
    - docker

windows:build:
  script:
    - configure --auto --windows
    - cd build
    - ninja
    - ninja install
    - cd ..
    - cmake -E copy_directory "C:\\Program Files\\fmps" target
  artifacts:
    expire_in: 1 day
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - target/
  stage: build
  tags:
    - windows

linux:smoke_test:
  script:
    - cp -r install/usr/local /usr/
    - cd /usr/local/bin/
    - ./fmps --help --version
  stage: smoke_test
  tags:
    - docker
  dependencies:
    - linux:build

windows:smoke_test:
  script:
    - cmake -E copy_directory target "C:/Program Files/fmps"
    - cd "C:/Program Files/fmps/bin/"  
    - fmps.exe --help --version
  stage: smoke_test
  tags:
    - windows
  dependencies:
    - windows:build

linux:unit_tests:
  script:
    - cp -r install/usr/local /usr/
    - cd /usr/local/bin/
    - ./unit_tests -s
  tags:
    - docker
  dependencies:
    - linux:build

windows:unit_tests:
  script:
    - cmake -E copy_directory target "C:/Program Files/fmps"
    - cd "C:/Program Files/fmps/bin/"
    - unit_tests.exe -s
  tags:
    - windows
  dependencies:
    - windows:build

linux:deploy_prod:
  script:
    - /bin/true
  stage: deploy
  environment: release
  artifacts:
    paths:
      - install/*
  only:
    - releases
  tags:
    - docker
  dependencies:
    - linux:build

windows:deploy_prod:
  script:
    - rem
  stage: deploy
  environment: release:windows
  artifacts:
    paths:
      - target/*
  only:
    - releases
  tags:
    - windows
  dependencies:
    - windows:build

linux:deploy_stage:
  script:
    - /bin/true
  stage: deploy
  environment: pre-release
  artifacts:
    paths:
      - install/*
  only:
    - release-*
  tags:
    - docker
  dependencies:
    - linux:build

windows:deploy_stage:
  script:
    - rem
  stage: deploy
  environment: pre-release
  artifacts:
    paths:
      - target/*
  only:
    - release-*
  tags:
    - windows
  dependencies:
    - windows:build
